### PR TITLE
Updated DotDict condition check in TypePrint method

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Hi Son,

works and is fine to me.

**Comment by namsonx** [comment]
Hello Holger,

Could you please help me merge this pull-request to avoid the failure of JP's selftest?

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi @namsonx ,  @HolQue ,
what is the status of this pull-request? Is this required?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

This pull-request is required for the feature that convert a dictionary output of JP to dotdict.
Could you please merge this pull-request?

Thank you,
Son

**Pull request merged**
